### ISSUE TITLE
Typed property must not be accessed before initialization

### ISSUE THREAD

**Issue by loskov** [Jurager/commerce#1]
https://github.com/Jurager/commerce/blob/028c8cd8df0a136e18974e834dcdebdfd59a1b9f/src/Model/Classifier.php#L25

https://github.com/Jurager/commerce/blob/028c8cd8df0a136e18974e834dcdebdfd59a1b9f/src/Model/Classifier.php#L89

**Comment by Jurager** [comment]
Fixed [Release 1.1](https://github.com/Jurager/commerce/releases/tag/1.1)
